# Generated by Django 2.1.2 on 2019-05-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goods',
            field=models.ManyToManyField(blank=True, related_name='item', to='products.Product'),
        ),
    ]
