# Generated by Django 2.2.3 on 2019-07-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190731_2145'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
