# Generated by Django 2.1.2 on 2019-05-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order_item', to='shopping_cart.Orderitem'),
        ),
    ]
